[Variables]

;==================\
; Update Info
;===/

CoreVersion=0.2

Changes3=New Skin "Volume Level".
Changes4=A new Minimal Design. Redesign of Start Screen

;==================\
; Function
;===/



[CoreVersion]
Measure=WebParser
URL=https://raw.githubusercontent.com/Nalinopek/AstroUI-Res/main/Variables/AstroVer.inc
Debug=2
Debug2File=#@#Version.inc
DynamicVariables=1
UpdateDivider=1
