[Variables]

NewVersion=0.2

UpdateAstroLinkDownload= https://raw.githubusercontent.com/Nalinopek/AstroUI-Res/main/Versions/AstroUI_#NewVersion#.rmskin


;=============
;Changes

Change1= --

Change2= --

;=============
;Function Web

[CHecker]
Measure=WebParser
URL=https://raw.githubusercontent.com/Nalinopek/AstroUI-Res/main/VarsWeb/AstroVer.inc
Debug=2
Debug2File=#ROOTCONFIGPATH#Addons\Updater\Updater\Vars\Check.inc
DynamicVariables=1
UpdateDivider=1
